# -*- mode: ruby -*-
# vi: set ft=ruby :

username = "ktakamat"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/trixie64"
  config.vm.box_version = "13.20260121.1"
  config.vm.define "#{username}S" do |s|
    s.vm.hostname = "#{username}S"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 1024
      libvirt.management_network_name = "iot-network"
    end

    s.vm.provision :shell, :inline => <<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl

      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --write-kubeconfig-mode 644" sh -

      echo "alias k='kubectl'" >> /home/vagrant/.bashrc

      if [ -d "/vagrant/confs" ]; then
        echo "Applying Kubernetes configurations..."
        sleep 20
        kubectl apply -f /vagrant/confs/
      fi
     SHELL
    end
  end
