# -*- mode: ruby -*-
# vi: set ft=ruby :

username = "ktakamat"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/trixie64"
  config.vm.box_version = "13.20260121.1"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 1024
    libvirt.management_network_name = "iot-network"
    libvirt.management_network_address = "192.168.56.0/24"
  end
  config.vm.define "#{username}S" do |control|
    control.vm.hostname = "#{username}S"
    control.vm.provider :libvirt do |libvirt|
      libvirt.management_network_mac = "52:54:00:e6:9a:05"
    end
    control.vm.provision :shell, :inline => <<-SHELL
      hostname
      sudo apt install curl -y
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_TOKEN=secret sh -
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc
    SHELL
  end
  config.vm.define "#{username}SW" do |control|
    control.vm.hostname = "#{username}SW"
    control.vm.provider :libvirt do |libvirt|
      libvirt.management_network_mac = "52:54:00:9b:64:7d"
    end
    control.vm.provision :shell, :inline => <<-SHELL
      hostname
      sudo apt install curl -y
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=secret sh -
    SHELL
  end
end

